name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main  # Executa quando há mudanças na branch principal

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production  # Defina o ambiente aqui, pode ser 'production', 'staging', etc.

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Criar artefato para deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Certifique-se de que está apontando para o diretório correto (./ significa raiz do repositório)

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v4
        with: 
          path: .

